name = deathstats
title = DeathStats
description = Cinematic pixel art death screen with zoom animation, detailed death causes, funny epitaphs, 3rd-person camera, lifetime statistics, and live scoreboard HUD.
author = SaKeL
min_minetest_version = 5.4.0
min_luanti_version = 5.4.0
supported_games = minetest_game, mineclonia, voxelibre, repixture, *
optional_depends = default, mcl_core, mcl_mobs, mobs_redo, bones, player_api, skinsdb, simple_skins, wardrobe, 3d_armor, mcl_armor, hbarmor, clothing, mcl_skins, mcl_death_drop, hudbars, hbhunger, stamina, hunger_ng, hbsprint, sprint_lite, unified_stamina, thirsty, edit_skin, collectible_skins, myappearance, nc_skins, u_skins
